# Generated by Django 5.2.17 on 2026-08-22 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField()),
                ('jobs_ran', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'get_latest_by': 'at',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('sort_key', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('import', 'CSV import'), ('sync', 'lmnapi sync')], default='sync', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='accounts.school')),
            ],
            options={
                'ordering': ['sort_key', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17)),
                ('hostname', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('sophomorix_group', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('import', 'CSV import'), ('sync', 'lmnapi sync')], default='sync', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.school')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='parc.room')),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('lmnapi', 'lmnapi'), ('csv_upload', 'CSV')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('success', 'Succeeded'), ('failed', 'Failed'), ('refused_guard', 'Refused by the volume guard')], max_length=20)),
                ('rooms_seen', models.PositiveIntegerField(default=0)),
                ('devices_seen', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.school')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyncDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('room_disappeared', 'Room disappeared'), ('room_renamed_suspected', 'Suspected room rename'), ('device_disappeared', 'Device disappeared')], max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='parc.syncrun')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_linbo_sync_at', models.DateTimeField(blank=True, null=True)),
                ('linbo_image', models.CharField(blank=True, max_length=200)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('fetch_status', models.CharField(blank=True, choices=[('ok', 'Observed'), ('unreachable', 'Unreachable'), ('forbidden', 'Forbidden')], max_length=20)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('refresh_requested_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='parc.device')),
            ],
            options={
                'indexes': [models.Index(fields=['refresh_requested_at'], name='parc_device_refresh_8dc0dc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('school', 'mac'), name='unique_device_mac_per_school'),
        ),
    ]
