# Generated by Django 5.2.17 on 2026-08-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='pxe',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='role',
            field=models.CharField(blank=True, choices=[('classroom-studentcomputer', 'Classroom computer (pupil)'), ('classroom-teachercomputer', 'Classroom computer (teacher)'), ('staffcomputer', 'Staff computer'), ('server', 'Server'), ('printer', 'Printer'), ('router', 'Router'), ('iponly', 'IP reservation only')], max_length=40),
        ),
    ]
