# Generated by Django 5.2.17 on 2026-08-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc', '0002_device_pxe_device_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='device',
            name='unique_device_mac_per_school',
        ),
        migrations.RemoveField(
            model_name='device',
            name='school',
        ),
        migrations.RemoveField(
            model_name='room',
            name='school',
        ),
        migrations.RemoveField(
            model_name='syncrun',
            name='school',
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('mac',), name='unique_device_mac'),
        ),
    ]
