# Generated by Django 5.2.17 on 2026-09-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc', '0003_remove_device_unique_device_mac_per_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestatus',
            name='fetch_status',
            field=models.CharField(blank=True, choices=[('ok', 'Observed'), ('no_data', 'No information'), ('forbidden', 'Forbidden')], max_length=20),
        ),
    ]
