# Generated by Django 5.2.17 on 2026-08-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('de', 'Deutsch'), ('fr', 'Français'), ('en', 'English')], max_length=10, verbose_name='Display language'),
        ),
    ]
