# Generated by Django 5.2.17 on 2026-08-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark')], max_length=10, verbose_name='Theme'),
        ),
    ]
