# Generated by Django 5.2.17 on 2026-08-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('member', 'Team member'), ('reporter', 'Reporter')], default='reporter', max_length=20),
        ),
    ]
