# Generated by Django 5.2.17 on 2026-08-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_admin_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('enroll', 'Enrolment'), ('role_change', 'Role change'), ('oidc_bind', 'OIDC binding'), ('anonymize', 'Anonymisation'), ('badge_award', 'Badge award'), ('badge_revoke', 'Badge withdrawn'), ('sync_decision', 'Sync decision'), ('sync_applied', 'Change applied by a sync'), ('visibility_change', 'Visibility change')], max_length=32),
        ),
    ]
