# Generated by Django 5.2.17 on 2026-08-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_unique_cn_per_school_while_named_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('badges', '0005_remove_badge_catalog_badge_has_no_school_and_more'),
        ('parc', '0003_remove_device_unique_device_mac_per_school_and_more'),
        ('tickets', '0006_remove_tag_unique_tag_per_school_and_more'),
    ]

    # Reordered by hand: makemigrations put the RemoveField first, and SQLite
    # remakes the whole table to drop a column -- rebuilding it with a
    # constraint that still names the column being removed. The constraint has
    # to go first.
    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_cn_per_school',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('cn',), name='unique_cn'),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
