# SPDX-License-Identifier: GPL-3.0-or-later
# Attachments are NEVER served directly: Django re-checks the parent ticket's
# visibility, then hands the bytes over here (D-21).
# Set ST_X_ACCEL_PREFIX=/protected in web.env.
location /protected/ {
    internal;
    alias /var/lib/school-tickets/media/;
}
