#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Fetch the two pinned CSS dependencies and generate the daisyUI import list.
# See specs/01-decisions.md, D-18.
#
#   ./tools/fetch-css-deps.sh          fetch everything, regenerate index.css
#   ./tools/fetch-css-deps.sh --list   regenerate index.css from what is on disk
#
# Updating means changing a number below and running this again. It fails loudly
# if a component of the list has disappeared -- that is the signal to read the
# migration notes, not to work around it.

set -eu

# --- The two pinned versions -------------------------------------------------
TAILWIND_VERSION="4.3.3"
DAISYUI_VERSION="5.7.20"

# The two scripts of D-17, vendored for the same reason as the CSS: a .deb must
# not depend on a CDN being up, nor change content between two builds.
HTMX_VERSION="2.0.10"
ALPINE_VERSION="3.16.2"

# --- The retained components (D-18: 34 of the 61 published) ------------------
# There is no automatic purge: every component imported is paid for whether it
# is used or not. The list is fixed once and moves rarely -- so it lives here,
# in the generator, and never in the hand-written app.css.
COMPONENTS="
alert avatar badge button card chat checkbox collapse dock drawer dropdown
fieldset fileinput indicator input label link list loading menu modal navbar
radio select skeleton stat status tab table textarea toast toggle tooltip
validator
"

# Order below mirrors daisyUI's own chunks.css. It is not decorative: the theme
# variables must be defined before anything reads them.
THEMES="light dark"
BASE="svg rootcolor scrollbar rootscrollgutter properties rootscrolllock reset"
UTILITIES="radius glass join typography"

# colors/properties.css is deliberately absent: 93 kB raw, and nothing here
# needs it -- Tailwind v4 already exposes the theme variables as utilities.
# It is the single biggest item in the whole package (D-18).
COLORS="states-extended properties-extended responsive-extended responsive states"

# --- Paths -------------------------------------------------------------------
ROOT=$(cd "$(dirname "$0")/.." && pwd)
DEST="$ROOT/assets/daisyui"
INDEX="$DEST/index.css"
BINARY="$ROOT/tools/tailwindcss"
VENDOR="$ROOT/static/vendor"

CDN="https://cdn.jsdelivr.net/npm/daisyui@${DAISYUI_VERSION}"
RELEASE="https://github.com/tailwindlabs/tailwindcss/releases/download/v${TAILWIND_VERSION}"

# --- Fetching ----------------------------------------------------------------
# --fail is NOT optional, and this is the one rule of this script.
#
# Verified on 2026-08-22: on a missing file jsDelivr answers 404 with a text
# body, and `curl -sL -o` exits 0 after writing that 65-byte error message into
# the .css file. Without --fail, an update in which daisyUI renamed a component
# produces a silently corrupted stylesheet that compiles without complaint.
# That is exactly what happened during the trial, with join.css.
fetch() {
    url="$1"
    out="$2"
    mkdir -p "$(dirname "$out")"
    if ! curl -sSL --fail --retry 2 -o "$out" "$url"; then
        echo "FAILED: $url" >&2
        echo "  If this is a component, it may have been renamed or removed in" >&2
        echo "  daisyUI ${DAISYUI_VERSION}. Read the release notes; do not work around it." >&2
        rm -f "$out"
        exit 1
    fi
}

fetch_daisyui() {
    echo "daisyUI ${DAISYUI_VERSION} -> assets/daisyui/"
    rm -rf "$DEST"
    for name in $THEMES;    do fetch "$CDN/theme/$name.css"      "$DEST/theme/$name.css"; done
    for name in $BASE;      do fetch "$CDN/base/$name.css"       "$DEST/base/$name.css"; done
    for name in $COMPONENTS; do fetch "$CDN/components/$name.css" "$DEST/components/$name.css"; done
    for name in $UTILITIES; do fetch "$CDN/utilities/$name.css"  "$DEST/utilities/$name.css"; done
    for name in $COLORS;    do fetch "$CDN/colors/$name.css"     "$DEST/colors/$name.css"; done
}

fetch_scripts() {
    echo "htmx ${HTMX_VERSION}, Alpine ${ALPINE_VERSION} -> static/vendor/"
    fetch "https://cdn.jsdelivr.net/npm/htmx.org@${HTMX_VERSION}/dist/htmx.min.js" \
        "$VENDOR/htmx.min.js"
    fetch "https://cdn.jsdelivr.net/npm/alpinejs@${ALPINE_VERSION}/dist/cdn.min.js" \
        "$VENDOR/alpine.min.js"
}

fetch_tailwind() {
    echo "Tailwind ${TAILWIND_VERSION} -> tools/tailwindcss"
    fetch "$RELEASE/tailwindcss-linux-x64" "$BINARY"
    chmod +x "$BINARY"
}

# --- Generating the import list ----------------------------------------------
# Tailwind cannot import a directory, so the files have to be enumerated. One
# generated file, one hand-written file, and no mixing of the two.
generate_index() {
    {
        echo "/* GENERATED by tools/fetch-css-deps.sh -- do not edit."
        echo "   daisyUI ${DAISYUI_VERSION}, $(echo "$COMPONENTS" | wc -w) of 61 components."
        echo "   Change the list in the script and run it again. */"
        for name in $THEMES;     do echo "@import \"./theme/$name.css\";"; done
        for name in $BASE;       do echo "@import \"./base/$name.css\";"; done
        for name in $COMPONENTS; do echo "@import \"./components/$name.css\";"; done
        for name in $UTILITIES;  do echo "@import \"./utilities/$name.css\";"; done
        for name in $COLORS;     do echo "@import \"./colors/$name.css\";"; done
    } > "$INDEX"
    echo "wrote $(wc -l < "$INDEX") imports to assets/daisyui/index.css"
}

# --- Main --------------------------------------------------------------------
if [ "${1:-}" = "--list" ]; then
    generate_index
    exit 0
fi

fetch_daisyui
fetch_scripts
fetch_tailwind
generate_index

cat <<EOF

Done. Compile with:
  ./tools/tailwindcss -i assets/app.css -o static/app.css --minify

Then compare the output size with the previous build: a sharp change means the
package structure moved (D-18, step 3).
EOF
