# Generated by Django 5.2.17 on 2026-08-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('accent', 'Accent'), ('neutral', 'Neutral'), ('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], help_text='Leave empty for a plain outline.', max_length=20, verbose_name='Colour'),
        ),
    ]
