# Generated by Django 5.2.17 on 2026-08-25 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.comment', verbose_name='Resolution'),
        ),
    ]
