# Generated by Django 5.2.17 on 2026-08-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='description_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
