# Generated by Django 5.2.17 on 2026-08-25 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc', '0003_remove_device_unique_device_mac_per_school_and_more'),
        ('tickets', '0005_ticket_description_edited_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_tag_per_school',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_school__49b445_idx',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='school',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='school',
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['visibility', 'status'], name='tickets_tic_visibil_5d5081_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_tag_slug'),
        ),
    ]
