# Generated by Django 5.2.17 on 2026-08-24 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ticket_opened', 'New ticket'), ('assigned', 'Assigned to you'), ('comment', 'New note'), ('resolved', 'Marked resolved'), ('reopened', 'Reopened'), ('sync_decisions', 'Estate changes to review')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_mutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'kind'), name='unique_mute_per_kind')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ticket_opened', 'New ticket'), ('assigned', 'Assigned to you'), ('comment', 'New note'), ('resolved', 'Marked resolved'), ('reopened', 'Reopened'), ('sync_decisions', 'Estate changes to review')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivery', models.CharField(choices=[('pending', 'Waiting'), ('sent', 'Sent'), ('muted', 'Muted by the recipient'), ('dropped', 'No longer visible'), ('no_device', 'No device subscribed'), ('failed', 'Delivery failed')], default='pending', max_length=12)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx'), models.Index(fields=['delivery', 'created_at'], name='notificatio_deliver_f0c306_idx')],
            },
        ),
    ]
