# Generated by Django 5.2.17 on 2026-08-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='delivery',
            field=models.CharField(choices=[('pending', 'Waiting'), ('sent', 'Sent'), ('muted', 'Muted by the recipient'), ('read', 'Already read in the application'), ('dropped', 'No longer visible'), ('no_device', 'No device subscribed'), ('failed', 'Delivery failed')], default='pending', max_length=12),
        ),
    ]
