# Generated by Django 5.2.17 on 2026-08-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mute',
            name='kind',
            field=models.CharField(choices=[('ticket_opened', 'New ticket'), ('assigned', 'Assigned to you'), ('comment', 'New note'), ('resolved', 'Marked resolved'), ('reopened', 'Reopened'), ('escalated', 'Now urgent'), ('sync_decisions', 'Estate changes to review')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('ticket_opened', 'New ticket'), ('assigned', 'Assigned to you'), ('comment', 'New note'), ('resolved', 'Marked resolved'), ('reopened', 'Reopened'), ('escalated', 'Now urgent'), ('sync_decisions', 'Estate changes to review')], max_length=20),
        ),
    ]
