# Generated by Django 5.2.17 on 2026-08-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='award_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
