# Generated by Django 5.2.17 on 2026-08-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_admin_roles'),
        ('badges', '0003_backfill_award_count'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='badge',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_catalog', True), ('school__isnull', True)), models.Q(('is_catalog', False), ('school__isnull', False)), _connector='OR'), name='catalog_badge_has_no_school'),
        ),
        migrations.AddConstraint(
            model_name='badge',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_badge_name_per_school'),
        ),
    ]
