# Generated by Django 5.2.17 on 2026-08-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_badge_catalog_badge_has_no_school_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='badge',
            name='catalog_badge_has_no_school',
        ),
        migrations.RemoveConstraint(
            model_name='badge',
            name='unique_badge_name_per_school',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='school',
        ),
        migrations.AddConstraint(
            model_name='badge',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_badge_name'),
        ),
    ]
