# Generated by Django 5.2.17 on 2026-08-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0005_remove_badge_catalog_badge_has_no_school_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['order', 'name', 'slug']},
        ),
        migrations.RemoveConstraint(
            model_name='badge',
            name='unique_badge_name',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='category',
        ),
        migrations.AddField(
            model_name='badge',
            name='family',
            field=models.CharField(blank=True, choices=[('network', 'Network'), ('workstation', 'Workstation'), ('presentation', 'Presentation equipment'), ('printing', 'Printing'), ('inventory', 'Workshop and inventory'), ('method', 'Diagnosis and method'), ('', '')], max_length=20),
        ),
        migrations.AddField(
            model_name='badge',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Offered'),
        ),
        migrations.AddField(
            model_name='badge',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='badge',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name'),
        ),
    ]
